### PR TITLE
Fix broken documentaiton links in lib.rs

### PR DESCRIPTION
**Pull request by its-luca**
The edited links in the main lib.rs documentation lead nowhere.

### CODE REVIEW

**Comment by tylerfanelli** [comment]
Thanks. Can you run `cargo readme` and amend the changes to the commit?

**Comment by its-luca** [comment]
If I understand correctly this would mean that the edited parts would no longer be a link in markdown (tested with the VSCode markdown renderer, not sure if Github would render that differently). Is that ok?

**Review by DGonzalezVillal — APPROVED** [review]

**Comment by tylerfanelli** [comment]
I think it should be fine.

**Review by tylerfanelli — APPROVED** [review]

**Comment by tylerfanelli** [comment]
@DGonzalezVillal can you review?

**Review by tylerfanelli — COMMENTED** [review]
So the links would no longer work on GitHub, but they would work on rust documentation?

**Comment by DGonzalezVillal** [comment]
> So the links would no longer work on GitHub, but they would work on rust documentation?

Yeah in his working repo, the links don't work on the GitHub. @tylerfanelli Is there a way keep it working both ways? What's the point of fixing it in one, if it'll break on the other.

**Comment by tylerfanelli** [comment]
We could just remove the [links these modules refer to](https://github.com/virtee/sev/blob/fb28b1dffc5b52aad055cff810cae094cf66c8d9/README.md?plain=1#L84-L85), as they are paths within the github repo. This would remove the links, but the labels `firmware` and `launch` would still be code blocks, indicating that they are source code modules.

**Comment by DGonzalezVillal** [comment]
> We could just remove the [links these modules refer to](https://github.com/virtee/sev/blob/fb28b1dffc5b52aad055cff810cae094cf66c8d9/README.md?plain=1#L84-L85), as they are paths within the github repo. This would remove the links, but the labels `firmware` and `launch` would still be code blocks, indicating that they are source code modules.

And would this have the links working on the rust documentation then?

**Comment by tylerfanelli** [comment]
No, they wouldn't be hyperlinks anymore. They would just be "code blocks" like `this`. Users would still understand that we're referring to a source code module then, which is fine (even though there is no hyperlink).

**Comment by DGonzalezVillal** [comment]
Looking at this link: https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html#motivation

Would doing:
`[firmware](sev::firmware)`
work in both secenarios?

**Comment by tylerfanelli** [comment]
Seems like it would work in Rust docs, have you tried in GitHub?

**Comment by DGonzalezVillal** [comment]
So with cargo-readme it won't work. Also cargo-readme has had limited contributions in the past 6 months.

I found this other project that has had recent contributions and you can generate links for both rust.doc and README. Would you be interested in switching to fix this issue?

https://github.com/orium/cargo-rdme

**Comment by tylerfanelli** [comment]
Sure, if it works better for us. Thanks for investigating this! Can you submit a PR with the changes?

**Pull request closed without merging**
