### PR TITLE
Remove SNP modules

### PR DESCRIPTION
**Pull request by tylerfanelli**
[virtee/snp](https://github.com/virtee/snp) now contains our SNP modules.

### CODE REVIEW

**Review by larrydewey — CHANGES_REQUESTED** [review]
We will need to bump the version on this, but it all makes sense. What is our roadmap for incorporating the [snp](https://github.com/virtee/snp) crate into sev?

**Comment by tylerfanelli** [comment]
Closes #33

**Comment by tylerfanelli** [comment]
@larrydewey I've updated the version (yet haven't published it on crates).

**Comment by fitzthum** [comment]
Have you considered using different rust features for the different functionality? I'm a bit skeptical about this being a breaking change.

**Comment by fitzthum** [comment]
@tylerfanelli 

It is reasonable to separate SEV and SNP functionality, but to me creating two separate repositories (assuming that's the plan) is not idiomatic. Rust has a number of ways to handle this kind of situation. For instance, you can use workspaces to have multiple libraries within one repository or you can use features to have one library with several different configurations. Both of these approaches are more flexible, allowing you to easily create new libs/features, share code between components without any synchronization problems, etc. In contrast splitting things into a new repo seems a bit blunt.

This also creates an inconvenience for people who are already using the project (which has already had a major release). With features you can easily control what is the default functionality so you could avoid breaking changes for people who are already using the crate.

Finally, I'm not convinced that maintaining two crates separately would be easier. It seems like that would lead to fewer eyes on each, less mutual development, and more administrative overhead.

**Comment by tylerfanelli** [comment]
@fitzthum 

Duly noted. Marking this as a draft for now and will explore using cargo workspaces.

**Pull request closed without merging**
