### PR TITLE
Updated launch library to use current IOCTls and gmem

### PR DESCRIPTION
**Pull request by DGonzalezVillal**
Updated the launch library to use INIT2 IOCTL and deprecate the old INIT IOCTLs. Created new functions to register encrypted memory for SNP. Updated SEV test to use INIT2. Updated the SNP launch test to use GMEM and support KVM GMEM for launch.

### CODE REVIEW

**Review by larrydewey — APPROVED** [review]
LGTM

**Review by larrydewey — CHANGES_REQUESTED** [review]
Actually, everything that utilizes an address as `u64` should include a `PhantomData` on the structure.

**Comment by tylerfanelli** [comment]
Is guest_memfd used here? I haven't been following much lately but I thought that replaced gmem?

**Comment by larrydewey** [comment]
> Is guest_memfd used here? I haven't been following much lately but I thought that replaced gmem?

That is what he is using. He will change the title of the PR :)

**Comment by tylerfanelli** [comment]
Thanks. Can I test this on the upstream kernel?

**Comment by DGonzalezVillal** [comment]
@tylerfanelli just fixed a small bug I had on the test, please feel free to test on upstream kernel.

**Comment by tylerfanelli** [comment]
can you point to the exact kernel you used to test?

**Review by larrydewey — APPROVED** [review]
LGTM!

**Comment by DGonzalezVillal** [comment]
> can you point to the exact kernel you used to test? 6.11?

Anything past 6.8-rc5 contains this update. I just tested on 6.11.0-rc3 and it worked.

**Review by tylerfanelli — APPROVED** [review]
LGTM, thanks!

**Comment by tylerfanelli** [comment]
@larrydewey @DGonzalezVillal Are we ready for a v5.0.0 release?

**Pull request merged**
